import assert from 'assert';
import fs from 'fs';
import { DEMO_SCENARIOS } from '../src/demo/demoScenarios.js';
import { runDemoScenario } from '../src/demo/demoRunner.js';
import { buildCartMandate } from '../src/cartMandate.js';
import { evaluateTransaction } from '../src/decision/transactionEvaluator.js';
import { evaluateApproval } from '../src/approvalGate.js';
import { runPaymentGuard } from '../src/paymentGuard.js';
import { logEvent, getTrail, clearTrails } from '../src/auditLog.js';
import { buyerAgentIdentity } from '../src/agentIdentity.js';

let passed = 0; let failed = 0;
function check(name, fn) { try { fn(); passed++; console.log(`  ✓ ${name}`); } catch (error) { failed++; console.log(`  ✕ ${name}\n      ${error.message}`); } }
const read = file => fs.readFileSync(new URL(`../${file}`, import.meta.url), 'utf8');
const html = read('public/index.html'), app = read('public/app.js'), css = read('public/style.css'), server = read('src/server.js'), fx = read('src/fxRates.js'), pkg = JSON.parse(read('package.json'));
const homeMarkup = html.slice(html.indexOf('<section class="mandate-home'), html.indexOf('<section id="controlShell"'));
const context = { buildCartMandate, evaluateTransaction, evaluateApproval, runPaymentGuard, logEvent };
clearTrails(['DEMO-HAPPY_PATH', 'DEMO-POLICY_BLOCK']);
console.log('\nProduct, demo, and deployment readiness');
check('PayMandate and Mandate naming is distinct in the primary chat', () => { assert.ok(html.includes('PayMandate')); assert.ok(homeMarkup.includes('>Mandate</span>')); assert.ok(homeMarkup.includes('AI Shopping Agent')); });
check('primary experience is WhatsApp-inspired chat, not the Control Center', () => { assert.ok(html.includes('aria-label="Agent chat"')); assert.ok(html.includes('commerceBrief')); assert.ok(css.includes('.commerce-brief')); });
check('Home is a dedicated chat DOM surface with no dashboard shell or technical sidebar', () => { for (const forbidden of ['All Features', 'Dashboard', 'Attack Mode', 'Mandate Chain', 'Control Center', 'data-goto="security"', 'data-goto="audit"']) assert.ok(!homeMarkup.includes(forbidden), forbidden); assert.ok(homeMarkup.includes('Message Mandate...')); assert.ok(homeMarkup.includes('AI Shopping Agent')); });
check('agent identity exposes real permissions and denies payment authority', () => { const a = buyerAgentIdentity({ agentSeed: 'A17', profile: {} }); assert.ok(a.permissions.allowed.includes('Negotiate with Merchant Agent')); assert.ok(a.permissions.denied.includes('Approve payment')); assert.ok(app.includes('Direct payment execution')); });
check('purchase rules are an active user-facing concept', () => { assert.ok(homeMarkup.includes('YOUR PURCHASE RULES')); assert.ok(app.includes('Only you can update these rules')); });
check('discovery cards show merchant, rating, price, and WHY', () => { assert.ok(app.includes('product-card-rating')); assert.ok(app.includes('product-card-meta')); assert.ok(app.includes('why-btn')); });
check('negotiation is visualized in the customer experience', () => { assert.ok(app.includes('SELLER NEGOTIATION')); assert.ok(app.includes('purchaseJourneyMarkup')); assert.ok(app.includes('Your limit stays fixed')); });
check('intent and actual deal are shown as independent facts', () => { assert.ok(app.includes('YOUR REQUEST')); assert.ok(app.includes('ACTUAL DEAL')); });
check('approval is explicit, amount-bound, and cannot be agent-owned', () => { assert.ok(app.includes('APPROVE ${inr(amount)}')); assert.ok(app.includes('Mandate cannot approve payment')); });
check('Payment Guard displays real check results before Razorpay TEST', () => { assert.ok(app.includes('PAYMANDATE PAYMENT GUARD')); assert.ok(app.includes('data.paymentGuard.checks')); });
check('policy blocks display intervention and payment not executed', () => { assert.ok(app.includes('PAYMANDATE INTERVENED')); assert.ok(app.includes('NOT EXECUTED')); });
check('Security Lab explains it hits the same product security path', () => { assert.ok(html.includes('security-product-path')); assert.ok(html.includes('Payment not executed')); });
check('Transaction Passport provides identifiers, WHY, TRACE, and read-only replay', () => { assert.ok(html.includes('TRANSACTION PASSPORT')); assert.ok(app.includes('READ ONLY · REPLAY NEVER EXECUTES A PAYMENT')); assert.ok(app.includes('passportTrace')); assert.ok(app.includes('passportReplay')); });
check('Judge Mode remains presentation-only', () => { assert.ok(html.includes('Normal Mode')); assert.ok(server.includes("app.post('/api/mode'")); });
check('official demos use fixed allow/block laptop figures', () => { assert.strictEqual(DEMO_SCENARIOS.happy_path.negotiatedPriceInr, 78000); assert.strictEqual(DEMO_SCENARIOS.policy_block.negotiatedPriceInr, 95000); assert.strictEqual(DEMO_SCENARIOS.policy_block.mandate.maxTransactionInr, 80000); });
check('happy demo is deterministic through real decision and guard engines', () => { const r = runDemoScenario('happy_path', context); assert.strictEqual(r.decision.finalDecision, 'ALLOW'); assert.strictEqual(r.paymentGuard.passed, true); assert.strictEqual(r.paymentAuthorized, true); });
check('block demo preserves proof and prevents payment', () => { const r = runDemoScenario('policy_block', context); assert.strictEqual(r.decision.finalDecision, 'BLOCK'); assert.strictEqual(r.paymentAuthorized, false); assert.ok(getTrail(r.transactionId).some(e => e.event === 'PAYMENT_GUARD_BLOCKED')); });
check('demo environment has deterministic FX with no background fetch', () => { assert.ok(fx.includes("process.env.NODE_ENV === 'demo'")); assert.ok(pkg.scripts.demo.includes('DEMO_MODE=true')); });
check('demo preflight is available', () => { assert.ok(pkg.scripts['demo:check']); assert.ok(fs.existsSync(new URL('../test/demo-preflight.js', import.meta.url))); });
check('public health exposes readiness, not secrets', () => { assert.ok(server.includes("app.get('/api/health'")); assert.ok(server.includes("app.get('/health'")); assert.ok(server.includes('razorpay_test_mode')); });
check('Docker deployment uses demo mode and keeps secrets outside the image context', () => { assert.ok(read('Dockerfile').includes('NODE_ENV=demo')); assert.ok(read('.dockerignore').includes('.env')); });
check('complete regression includes observability, product, and end-to-end checks', () => { assert.ok(pkg.scripts.test.includes('check:observability')); assert.ok(pkg.scripts.test.includes('check:product')); assert.ok(pkg.scripts.test.includes('test:e2e')); });
clearTrails(['DEMO-HAPPY_PATH', 'DEMO-POLICY_BLOCK']);
console.log(`\n${'─'.repeat(58)}\nProduct verification: ${passed} checks passed${failed ? `, ${failed} failed` : ''}.\n${'─'.repeat(58)}`);
if (failed) process.exitCode = 1;
