/** Stable API error vocabulary. Clients must branch on code, never prose. */
export const ERROR_CODE = Object.freeze({
  INVALID_REQUEST: 'INVALID_REQUEST',
  INVALID_TRANSACTION_STATE: 'INVALID_TRANSACTION_STATE',
  DEAL_INVALID: 'DEAL_INVALID',
  STALE_DEAL: 'STALE_DEAL',
  MANDATE_LIMIT_EXCEEDED: 'MANDATE_LIMIT_EXCEEDED',
  POLICY_BLOCKED: 'POLICY_BLOCKED',
  TRUST_BLOCKED: 'TRUST_BLOCKED',
  RISK_REVIEW: 'RISK_REVIEW',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  APPROVAL_EXPIRED: 'APPROVAL_EXPIRED',
  PAYMENT_GUARD_BLOCKED: 'PAYMENT_GUARD_BLOCKED',
  DUPLICATE_PAYMENT: 'DUPLICATE_PAYMENT',
  PAYMENT_RECOVERY_REQUIRED: 'PAYMENT_RECOVERY_REQUIRED',
  NEGOTIATION_EXPIRED: 'NEGOTIATION_EXPIRED'
});
